In [8]:
import numpy as np

QUESTION : 1 

In [24]:
a = np.random.random((3,3,3))
print(a)

[[[0.62774199 0.35607709 0.41602559]
  [0.34665216 0.79560831 0.17666725]
  [0.71383694 0.54018524 0.59412831]]

 [[0.33962128 0.82878435 0.65654101]
  [0.74619734 0.0937322  0.83963601]
  [0.76779698 0.82901176 0.92079927]]

 [[0.66906503 0.83386728 0.89010057]
  [0.35154414 0.41105882 0.88508587]
  [0.89478174 0.72624976 0.07117545]]]


QUESTION : 2

In [25]:
a1 = np.diag([1,2,3,4,5])
print(a1)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


QUESTION : 3

In [35]:
a2 = np.zeros((8,8),dtype = int)
a2[1::2,::2] = 1
a2[::2,1::2] = 1
print(a2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


QUESTION : 4

In [38]:
from sklearn.preprocessing import normalize
matrix = np.random.random((5,5))
print('Original Matrix::')
print(matrix)

Original Matrix::
[[0.07763395 0.75291914 0.76282415 0.81497797 0.02208226]
 [0.17279859 0.79623705 0.1904842  0.88739735 0.25555681]
 [0.14297889 0.95040755 0.82096377 0.44783662 0.93474247]
 [0.70284075 0.29996127 0.81420518 0.96062583 0.38831082]
 [0.1882044  0.64361445 0.1823625  0.43581276 0.9323693 ]]


In [48]:
normalized_matrix = normalize(matrix,axis=1,norm='max')
print('Normalized Matrix::')
print(normalized_matrix)

Normalized Matrix::
[[0.09525896 0.92385214 0.93600585 1.         0.02709553]
 [0.19472516 0.89727229 0.21465492 1.         0.28798465]
 [0.15043955 1.         0.86380181 0.47120482 0.98351751]
 [0.73164881 0.31225609 0.84757786 1.         0.40422692]
 [0.20185607 0.69029992 0.19559042 0.46742504 1.        ]]


QUESTION : 5

In [57]:
arr1 = list(range(20))
arr2 = list(range(11,25,2)) 
print('First Array',arr1)
print('Second Array',arr2)

First Array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
Second Array [11, 13, 15, 17, 19, 21, 23]


In [62]:
print('Common Values::')
for i in arr1:
    for j in arr2:
        if i == j :
            print(i,end=' ')
        else:
            continue

Common Values::
11 13 15 17 19 

 QUESTION : 6

In [63]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


QUESTION: 7

In [74]:
r = int(input('Enter the number of elements in arr1::'))
arr1 = list()
arr2 = list() 
for i in range(r):
    n1 = int(input(f'Enter number {i+1}::'))
    arr1.append(n1)
s = int(input('Enter the number of elemnts  in arr2::'))
for j in range(s):
    n2 = int(input(f'Enter number {j+1}::'))
    arr2.append(n2)
print('First Array',arr1)
print('Second Array',arr2)
arr1.sort();
arr2.sort();

if len(arr1)!=len(arr2):
    print('Arrays Not Equal!!!')
f = 1
for i in range(0,r-1):
        if arr1[i] != arr2[i] :
            f = 0
        else:
            continue
if f==0:
    print('Arrays Not Equal!!!')
else:
    print('Arrays Equal!!!')

Enter the number of elements in arr1::5
Enter number 1::5
Enter number 2::4
Enter number 3::9
Enter number 4::8
Enter number 5::7
Enter the number of elemnts  in arr2::5
Enter number 1::8
Enter number 2::9
Enter number 3::4
Enter number 4::5
Enter number 5::7
First Array [5, 4, 9, 8, 7]
Second Array [8, 9, 4, 5, 7]
Arrays Equal!!!


QUESTION : 8

In [77]:
b = np.random.random(10)
print('Original Array::')
print(b)

Original Array::
[0.97628056 0.11605445 0.51994397 0.44775016 0.16984904 0.3267557
 0.11709408 0.68108359 0.82781494 0.3824763 ]


In [78]:
b[b.argmax()] = 0
print('Updated Array::')
print(b)

Updated Array::
[0.         0.11605445 0.51994397 0.44775016 0.16984904 0.3267557
 0.11709408 0.68108359 0.82781494 0.3824763 ]


QUESTION : 9

In [80]:
print(np.zeros((3,3),dtype = int))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


QUESTION : 10

In [86]:
np.mean?

In [85]:
print('Original Matrix::')
m = np.random.rand(5,3)
print(m)

Original Matrix::
[[0.79717429 0.33142181 0.81083993]
 [0.73524    0.78482059 0.00406138]
 [0.59962152 0.77972909 0.20284992]
 [0.01449573 0.99341141 0.02885053]
 [0.87816802 0.75393431 0.26995968]]


In [87]:
n = m - m.mean(axis=1,keepdims = True)
print('Updated Matrix::')
print(n)

Updated Matrix::
[[ 0.15069561 -0.31505687  0.16436126]
 [ 0.22719934  0.27677993 -0.50397927]
 [ 0.07222134  0.25232891 -0.32455025]
 [-0.33109016  0.64782552 -0.31673536]
 [ 0.24414735  0.11991364 -0.36406099]]


QUESTION : 11

In [95]:
x = np.ones(10)
i = np.random.randint(0,len(x),20)
x += np.bincount(i, minlength=len(x))
print(x)

[3. 4. 3. 3. 4. 2. 3. 1. 4. 3.]


In [89]:
QUESTION :12

In [93]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,(3, 3))
print('First Matrix::')
print(a)
print('Second Matrix::')
print(b)
print('Diagonal of dot product')
print(np.diag(np.dot(a,b)))

First Matrix::
[[5 9 8]
 [8 7 3]
 [2 8 4]]
Second Matrix::
[[2 9 4]
 [6 0 8]
 [4 3 7]]
Diagonal of dot product
[ 96  81 100]


QUESTION : 13

In [100]:
x = np.random.randint(0, 10,8)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[5 2 9 0 8 4 2 7]
Most frequent value in the above array:
2


QUESTION : 14

In [107]:
y = np.arange(10)
print("Original array:")
print(y)
np.random.shuffle(y)
n = 1
print (y[np.argsort(y)[-n:]])

Original array:
[0 1 2 3 4 5 6 7 8 9]
[9]


QUESTION : 15

In [108]:
x1 = np.array([1,2,3,4])
x2 = np.array(['Red','Green','Blue','Orange'])
x3 = np.array([10,15,20,25])
result= np.core.records.fromarrays([x1, x2, x3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 10)
(2, 'Green', 15)
(3, 'Blue', 20)
